### ISSUE TITLE
Error writing to database

### ISSUE THREAD

**Issue by JorgeDHernandez** [h5p/moodle-mod_hvp#378] opened 2020-10-26 13:34 UTC
Good day!

Thanks for such a wonderful plugin!

I share the following error that our Moodle 3.5.1+ throws (Buil: 20180824), when trying to customize the ES_CO language string

×Debug info: Duplicate entry 'es_co-107-reusecontent' for key 'mdl_toolcust_lancomstr_uix'
INSERT INTO mdl_tool_customlang (lang,componentid,stringid,original,master,timemodified,outdated,local,timecustomized) VALUES(?,?,?,?,?,?,?,?,?)
[array (
0 => 'es_co',
1 => '107',
2 => 'reusecontent',
3 => 'Reuse Content',
4 => 'Reutilizar contenido',
5 => 1603717919,
6 => 0,
7 => NULL,
8 => NULL,
)]
Error code: dmlwriteexception
×Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1329 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1375 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 191 of /admin/tool/customlang/locallib.php: call to mysqli_native_moodle_database->insert_record()
line 60 of /admin/tool/customlang/index.php: call to tool_customlang_utils::checkout()

Doing the query (SELECT * FROM prefix_tool_customlang_components WHERE id=107) to the database gives the following result:

id	name	version
107	mod_hvp	2020080400

Hopefully they can review it

Thank you very much!

Happy day!

**Comment by thomasmars** [comment] 2020-10-27 08:10
Hi, this sounds like a duplicate of https://github.com/h5p/moodle-mod_hvp/issues/313. Can you check if the solution propsed at https://github.com/h5p/moodle-mod_hvp/issues/313#issuecomment-551056418 can solve your issue ?

**Closed** 2021-04-08 12:48 UTC
