### ISSUE TITLE
H5P Interactive Video: issue regarding saving modifications done on existing content

### ISSUE THREAD

**Issue by AmelieSOUBRAT** [h5p/moodle-mod_hvp#469] opened 2022-10-06 16:17 UTC
Hello,

We identified a problem on a few interactive videos created on Moodle v3.10.10+ (Build: 20220318).

After editing the videos, the modifications are not taken into account: the 'Save' button is inactive.

There is the following error message in the web console when the 'Save' button is clicked: 'Uncaught TypeError: Cannot read property 'field' of undefined".

We are using the language 'French (français)'.
By editing the language in 'Editing texts and translation' and choosing 'English' instead, the problem seems to be solved.

Many thanks for your help.

**Comment by fnoks** [comment] 2022-10-25 11:26
I believe this is a duplicate of https://github.com/h5p/h5p-interactive-video/issues/258

**Closed by fnoks** 2022-10-25 11:26 UTC
