### ISSUE TITLE
Version 1.1.0 of the reporting module is required to render this report. Currently installed: 1.0.0

### ISSUE THREAD

**Issue by yao9394** [h5p/moodle-mod_hvp#302] opened 2019-09-16 04:56 UTC
Hi 

Could anyone please advise if this is a known issue? 

https://h5p.org/comment/29609 
https://h5p.org/node/577412

Will there be a fix release for this issue? 

Thank you

John

**Comment by thomasmars** [comment] 2019-09-16 07:30
Support for alternatives in FitB reports is not implemented yet. 
Follow https://h5ptechnology.atlassian.net/browse/HFP-2854 for updates.

**Comment by yao9394** [comment] 2019-09-16 23:54
Hi @thomasmars 
Thank you for your prompt reply. Will there be a timeline for this work ?
Thanks
John

**Comment by yao9394** [comment] 2019-09-17 00:21
Hi @thomasmars 

Is changing the version number the ideal fix for this issue? If yes, can we submit a PR for this?
Otherwise, if possible, please advise your plan on this?
Thank you

John

**Comment by thomasmars** [comment] 2019-09-17 06:48
No, the rendering of the report in the reporting module has to be changed to support the "https://h5p.org/x-api/alternatives" extension in the xAPI event that Fill in the Blanks sends.
If you just increase the reporting version, the reports for Fill in the Blanks content with many alternatives will grow exponentially and will crash if there are many enough alternatives. I don't have a timeline for this, feel free to comment on the issue and watch it for progress.

**Comment by jwalits** [comment] 2019-12-17 04:26
Hi

Has there been any update on this issue?

Thanks,
Jay

**Comment by jwalits** [comment] 2019-12-23 04:36
Hi,

I've been investigating this issue. After I changed the version number in the H5PReport class to '1.1.0', I've been testing the reports with Fill in the Blanks data, to me it appears that the Report class is able to handle the FitB data correctly? Do you have a particular concern around handling of the data that we should look at?

If updating the version number appears to be a suitable fix, can we submit a PR for this?

Regards,
Jay

**Comment by thomasmars** [comment] 2019-12-23 17:55
Hi Jay,
If you create a blanks with multiple alternatives per blank they will not show in the report because the report renderer does not know how to render the alternatives extension. It was introduced because the correct answers definition of the xapi event grows exponentially with number of alternatives, which would cause the content type to crash.
So just increasing the patch version will not help show the alternatives per answer in the report.

**Comment by jwalits** [comment] 2019-12-23 22:31
Hi @thomasmars,

Thanks for the feedback.

Regards,
Jay

**Comment by jwalits** [comment] 2019-12-24 00:53
Hey Thomas,

Based on your feedback, I have updated the FitB report to handle "https://h5p.org/x-api/alternatives" extension

When you have a chance. please see: https://github.com/h5p/h5p-php-report/pull/7

Hope you have a Merry Christmas and Happy New Year :-)

Kind Regards,
Jay

**Comment by jwalits** [comment] 2020-04-09 00:50
Hi,

Any update on this issue? If you have a chance, it would be great to get some feedback on the PR I submitted earlier on this issue?

Please let me know,

Thanks,
Jay

**Comment by thomasmars** [comment] 2020-04-09 11:57
Hi, I've had a look at the pull request and made some comments about it.

**Comment by jwalits** [comment] 2020-04-13 23:11
Thanks @thomasmars,

Appreciate your feedback. I'll have a look and update the code as necessary.

Regards,
Jay

**Comment by jwalits** [comment] 2020-04-16 04:48
Hi @thomasmars,

I have updated the PR as per the feedback. Please review and provide feedback when possible.

Regards,
Jay

**Comment by philrankinBB** [comment] 2020-08-27 01:25
Hi,

Just wondering if there are any updates about this.

Thanks,
Phil.

**Comment by haietza** [comment] 2020-09-02 13:51
We are also seeing this error in the Interactive Video content type. Will the patch posted above work for all content type reports? If not, can it be applied to them all with the next release of the plugin? 

Are there any workarounds for accessing this content in the meantime?

Thank you!

**Comment by rlorenzo** [comment] 2020-09-03 17:14
@jwalits I see that the pull request you made has a code conflict: type-processors/fill-in-processor.class.php

If you can fix it then hopefully a new version can be released: https://github.com/h5p/h5p-php-report/pull/7

**Comment by golenkovm** [comment] 2021-05-21 09:36
Thanks for merging in https://github.com/h5p/h5p-php-report/pull/7 @thomasmars 
Should we open the same pull request for the stable branch?
FYI @jwalits

**Comment by thomasmars** [comment] 2021-05-21 09:43
No, master will be merged to release when preparing for release, then merged to stable once regression tested and released.

**Closed by thomasmars** 2021-05-21 09:43 UTC

**Comment by golenkovm** [comment] 2021-06-11 04:59
Hey @thomasmars 
Could you please let us know if there any ETA on when it might be available in stable branch?
Cheers

**Comment by thomasmars** [comment] 2021-06-11 12:42
This is released as part of mod_hvp 1.22.3
