### ISSUE TITLE
Moodle 4.5 compatibility

### ISSUE THREAD

**Issue by guckuck** [h5p/moodle-mod_hvp#571] opened 2024-10-28 17:23 UTC
Are there any plans for the Moodle 4.5 compatibility? I use this great plugin very often but there seams to be a problem when updating to 4.5.

```
Database transaction aborted automatically in /var/www/moodle/admin/cli/upgrade.php
Default exception handler: Fehler: Undefined constant "MESSAGE_DEFAULT_LOGGEDIN" Debug:
Error code: generalexceptionmessage
* line 37 of /mod/hvp/db/messages.php: Error thrown
* line 692 of /lib/messagelib.php: call to require()
* line 487 of /lib/messagelib.php: call to message_get_providers_from_file()
* line 629 of /lib/upgradelib.php: call to message_update_processors()
* line 771 of /lib/upgradelib.php: call to upgrade_component_updated()
* line 1937 of /lib/upgradelib.php: call to upgrade_plugins()
* line 274 of /admin/cli/upgrade.php: call to upgrade_noncore()

!!! Fehler: Undefined constant "MESSAGE_DEFAULT_LOGGEDIN" !!!
!!
Error code: generalexceptionmessage !!
!! Stack trace: * line 37 of /mod/hvp/db/messages.php: Error thrown
* line 692 of /lib/messagelib.php: call to require()
* line 487 of /lib/messagelib.php: call to message_get_providers_from_file()
* line 629 of /lib/upgradelib.php: call to message_update_processors()
* line 771 of /lib/upgradelib.php: call to upgrade_component_updated()
* line 1937 of /lib/upgradelib.php: call to upgrade_plugins()
* line 274 of /admin/cli/upgrade.php: call to upgrade_noncore()
!!
```

Best regards
Kay

**Comment by ldidry** [comment] 2024-10-30 14:06
You can manually apply the patch of https://github.com/h5p/moodle-mod_hvp/pull/566/files.

**Comment by ldidry** [comment] 2024-10-30 14:06
(duplicate of #562, btw)

**Comment by guckuck** [comment] 2024-10-30 14:08
Thank you very much. I will try that.

**Closed** 2024-11-05 16:05 UTC
